"""empty message

Revision ID: b6dde7f3de43
Revises: e019a2e60344
Create Date: 2018-08-30 19:53:04.730461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6dde7f3de43'
down_revision = 'e019a2e60344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pembeli',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('alamat', sa.String(length=200), nullable=False),
    sa.Column('telepon', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pembeli_email'), 'pembeli', ['email'], unique=False)
    op.create_index(op.f('ix_pembeli_nama_lengkap'), 'pembeli', ['nama_lengkap'], unique=False)
    op.create_table('produk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=80), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(length=254), nullable=False),
    sa.Column('gambar', sa.String(length=254), nullable=False),
    sa.Column('cakupan', sa.String(length=50), nullable=False),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('produsen_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ),
    sa.ForeignKeyConstraint(['produsen_id'], ['produsen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produk_cakupan'), 'produk', ['cakupan'], unique=False)
    op.create_index(op.f('ix_produk_gambar'), 'produk', ['gambar'], unique=False)
    op.create_index(op.f('ix_produk_harga'), 'produk', ['harga'], unique=False)
    op.create_index(op.f('ix_produk_nama'), 'produk', ['nama'], unique=False)
    op.create_index(op.f('ix_produk_stok'), 'produk', ['stok'], unique=False)
    op.create_table('pesanan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('waktu_butuh', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('produk_id', sa.Integer(), nullable=True),
    sa.Column('pembeli_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pembeli_id'], ['pembeli.id'], ),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pesanan_jumlah'), 'pesanan', ['jumlah'], unique=False)
    op.create_index(op.f('ix_pesanan_status'), 'pesanan', ['status'], unique=False)
    op.create_index(op.f('ix_pesanan_waktu_butuh'), 'pesanan', ['waktu_butuh'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pesanan_waktu_butuh'), table_name='pesanan')
    op.drop_index(op.f('ix_pesanan_status'), table_name='pesanan')
    op.drop_index(op.f('ix_pesanan_jumlah'), table_name='pesanan')
    op.drop_table('pesanan')
    op.drop_index(op.f('ix_produk_stok'), table_name='produk')
    op.drop_index(op.f('ix_produk_nama'), table_name='produk')
    op.drop_index(op.f('ix_produk_harga'), table_name='produk')
    op.drop_index(op.f('ix_produk_gambar'), table_name='produk')
    op.drop_index(op.f('ix_produk_cakupan'), table_name='produk')
    op.drop_table('produk')
    op.drop_index(op.f('ix_pembeli_nama_lengkap'), table_name='pembeli')
    op.drop_index(op.f('ix_pembeli_email'), table_name='pembeli')
    op.drop_table('pembeli')
    # ### end Alembic commands ###
