"""empty message

Revision ID: e019a2e60344
Revises: 8fbe096877bf
Create Date: 2018-08-30 15:24:50.507698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e019a2e60344'
down_revision = '8fbe096877bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kategori_nama'), 'kategori', ['nama'], unique=False)
    op.create_table('produsen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=80), nullable=False),
    sa.Column('nama_usaha', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('alamat', sa.String(length=200), nullable=False),
    sa.Column('telepon', sa.String(length=14), nullable=False),
    sa.Column('waktu_mulai', sa.DateTime(), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produsen_email'), 'produsen', ['email'], unique=False)
    op.create_index(op.f('ix_produsen_nama_lengkap'), 'produsen', ['nama_lengkap'], unique=False)
    op.create_index(op.f('ix_produsen_waktu_mulai'), 'produsen', ['waktu_mulai'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produsen_waktu_mulai'), table_name='produsen')
    op.drop_index(op.f('ix_produsen_nama_lengkap'), table_name='produsen')
    op.drop_index(op.f('ix_produsen_email'), table_name='produsen')
    op.drop_table('produsen')
    op.drop_index(op.f('ix_kategori_nama'), table_name='kategori')
    op.drop_table('kategori')
    # ### end Alembic commands ###
